### PR TITLE
map vocabularylisturl to vocabularyserviceurl if present

### PR DESCRIPTION
**Pull request by jonescc**

### CODE REVIEW

**Comment by julian1** [comment]
Hi @jonescc 

Have you checked whether these validate? Against 19139 and mcp2?

Also, it would be clearer if the whitespace was in a separate commit to make it easier to review. (You only need type-3 chomsky grammar to distinguish this).

**Comment by julian1** [comment]
Are you sure we're not duplicating information that's in both skos and the metadata record. I think as a policy we decided to avoid using the mcp2 extension fields, in order that we don't have to do additional updating the record just because the skos changes.

**Comment by jonescc** [comment]
No - in this case the reference is to the vocabulary list in which the term is defined.   These are legacy records that don't conform to portal requirements - just trying not to lose this information.

**Comment by jonescc** [comment]
whitespace changes reverted - they were unintentional

**Comment by julian1** [comment]
Why are these records using the vocabularyServiceURL and our 123 records don't?

**Comment by julian1** [comment]
I'm asking for my own benefit.

**Comment by jonescc** [comment]
Because they are cf terms

**Comment by julian1** [comment]
Ahh got it.

**Pull request merged**
