### PR TITLE
Merge imos schema plugin changes to 2.10.x schema plugins branch

### PR DESCRIPTION
**Pull request by jonescc**
Changes to be pushed up to core geonetwork schema plugins branch

Resolves differences between core 2.10.x geonetwork mcp 2.0 schema plugin and IMOS 2.10.x mcp 2.0 schema plugin

Will need to change our Geonetwork to use organisation instead of orgName index key for the organisation facet to use this schema plugin so that I could return the orgName index key to its core behaviour.

MCP 2.0 draft to MCP 2.0 ratified changes to be pushed up separately for review by Simon Pigot

### CODE REVIEW

**Comment by julian1** [comment]
I'm looking.

**Comment by julian1** [comment]
Have you tested this with portal?

**Comment by jonescc** [comment]
Yes, portal works with these changes.  Only thing missing is the temporal aggregation codes - which should be packaged up with MCP2.0 ratification changes.

**Comment by jonescc** [comment]
@julian1 - removed unused namespaces

**Comment by julian1** [comment]
@jonescc I'm getting the following, when trying to run

```
2016-01-11 14:35:04,428 ERROR [jeeves.service] -    -> exception during transformation for : main.home
2016-01-11 14:35:04,428 ERROR [jeeves.service] -    ->  (C) stylesheet : /var/lib/tomcat7/webapps/geonetwork/xsl/main-page.xsl
2016-01-11 14:35:04,428 ERROR [jeeves.service] -    ->  (C) message    : Failed to compile stylesheet. 56 errors detected.
2016-01-11 14:35:04,428 ERROR [jeeves.service] -    ->  (C) exception  : TransformerConfigurationException
2016-01-11 14:35:04,429 INFO  [jeeves.service] -    -> dispatching to error for : main.home
2016-01-11 14:35:04,438 INFO  [jeeves.service] -      -> transforming with stylesheet : /var/lib/tomcat7/webapps/geonetwork/xsl/error.xsl
2016-01-11 14:35:04,475 INFO  [jeeves.service] -      -> end error transformation for : main.home
2016-01-11 14:35:04,475 INFO  [jeeves.service] -    -> error ended for : main.home
```

**Comment by julian1** [comment]
Tested in GN and Portal. Works well!

**Pull request merged**
