### PR TITLE
Add WMS filter checking to prod records

### PR DESCRIPTION
**Pull request by anguss00**
@ccmoloney I was thinking keeping the list of excluded collections in the file as it just needs to match on the layer name, but open to your opinions on best practice here

### CODE REVIEW

**Comment by ccmoloney** [comment]
I guess the list isn't going to change often - so maybe hard-coding will do the job for now?  Just need to make folk aware that if they want to add a no-filters collection - then the list has to be updated + the xsl redeployed.

**Comment by anguss00** [comment]
Yes, agreed. But if we have the list in a separate xml, won't it have to be in the schema-plugins dir anyway?

**Comment by ccmoloney** [comment]
It could be read from a URL.

**Comment by anguss00** [comment]
Good point. I think I'll look at doing that TBH. Worth storing the file somewhere (ie s3) and then being able to read it

**Comment by ccmoloney** [comment]
Do we have any non-filter layers yet?  Ie: should the excludedCollections list contain any entries?

**Comment by anguss00** [comment]
Good question, will need to check with @smancini?

**Pull request merged**
